openapi: 3.1.0
info:
  title: Order Management System API
  description: REST API for managing orders
  version: 1.0.0
servers:
  - url: https://localhost:5001
    description: Local development server
paths:
  /api/orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: A list of orders
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '201':
          description: The created order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /api/orders/{id}:
    get:
      summary: Get an order by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the order to retrieve
          schema:
            type: string
      responses:
        '200':
          description: The order with the specified ID
        '404':
          description: Order not found
    delete:
      summary: Delete an order by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the order to delete
          schema:
            type: string
      responses:
        '204':
          description: Order deleted successfully
components:
  schemas:
    OrderInput:
      type: object
      properties:
        orderName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
    Order:
      type: object
      properties:
        id:
          type: string
        orderName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number